In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('/content/covid_worldwide.xls.csv')
df.head()

,Serial Number,Country,Total Cases,Total Deaths,Total Recovered,Active Cases,Total Test,Population
0,1,USA,"104,196,861","1,132,935","101,322,779","1,741,147","1,159,832,679","334,805,269"
1,2,India,"44,682,784","530,740","44,150,289","1,755","915,265,788","1,406,631,776"
2,3,France,"39,524,311","164,233","39,264,546","95,532","271,490,188","65,584,518"
3,4,Germany,"37,779,833","165,711","37,398,100","216,022","122,332,384","83,883,596"
4,5,Brazil,"36,824,580","697,074","35,919,372","208,134","63,776,166","215,353,593"

In [3]:
df.replace("N/A", np.nan, inplace=True)

In [4]:
df_cleaned = df.dropna()

In [5]:
print(df_cleaned)

     Serial Number                Country  Total Cases Total Deaths  \
0                1                    USA  104,196,861    1,132,935
1                2                  India   44,682,784      530,740
2                3                 France   39,524,311      164,233
3                4                Germany   37,779,833      165,711
4                5                 Brazil   36,824,580      697,074
..             ...                    ...          ...          ...
217            218               Anguilla        3,904           12
218            219                  Macao        3,488          120
219            220  Saint Pierre Miquelon        3,452            2
220            221      Wallis and Futuna        3,427            7
224            225             Montserrat        1,403            8

    Total Recovered Active Cases     Total Test     Population
0       101,322,779    1,741,147  1,159,832,679    334,805,269
1        44,150,289        1,755    915,265,788  1,406,631,776
2        39,264,546       95,532    271,490,188     65,584,518
3        37,398,100      216,022    122,332,384     83,883,596
4        35,919,372      208,134     63,776,166    215,353,593
..              ...          ...            ...            ...
217           3,879           13         51,382         15,230
218           3,357           11          7,850        667,490
219           2,449        1,001         25,400          5,759
220             438        2,982         20,508         10,982
224           1,376           19         17,762          4,965

[195 rows x 8 columns]

In [6]:
df_cleaned.to_csv("covid_cleaned.csv", index=False)